# Generated by Django 2.2 on 2019-07-06 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='guide',
            new_name='guides',
        ),
    ]
