# Generated by Django 2.2 on 2019-07-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('area', models.CharField(max_length=10)),
                ('picture', models.FileField(default='', upload_to='')),
            ],
        ),
    ]
